x = {'city': 'Miami',
     'left':
         {'city': 'Jacksonville', 'left':
             {'city': 'Macon', 'left':
                 {'city': 'Atlanta',
                  'left': {'city': 'Chattanooga',
                           'left': {
                               'city': 'Nashville',
                               'left': {
                                   'city': 'Bowling_Green',
                                   'left': {
                                       'city': 'Louisville',
                                       'left': {
                                           'city': 'Indianapolis',
                                           'left': {
                                               'city': 'Fort_Wayne',
                                               'left': {
                                                   'city': 'Ann_Arbor',
                                                   'left': {
                                                       'city': 'Detroit',
                                                       'left': {
                                                           'city': 'Canada',
                                                           'left': None,
                                                           'right': None},
                                                       'right': None},
                                                   'right': None},
                                               'right': None},
                                           'right': None},
                                       'right': None},
                                   'right': {
                                       'city': 'Lexington',
                                       'left': {
                                           'city': 'Cincinnati',
                                           'left': {
                                               'city': 'Toledo',
                                               'left': {
                                                   'city': 'Detroit_2',
                                                   'left': {
                                                       'city': 'Canada_3',
                                                       'left': None,
                                                       'right': None},
                                                   'right': None},
                                               'right': None},
                                           'right': None},
                                       'right': None}},
                               'right': None},
                           'right': {
                               'city': 'Knoxville',
                               'left': {
                                   'city': 'Abingdon',
                                   'left': {
                                       'city': 'Roanoke',
                                       'left': {
                                           'city': 'Lewisburg',
                                           'left': {
                                               'city': 'Charleston',
                                               'left': {
                                                   'city': 'Athens',
                                                   'left': {
                                                       'city': 'Akron',
                                                       'left': {
                                                           'city': 'Erie',
                                                           'left': {
                                                               'city': 'Buffalo-3',
                                                               'left': {
                                                                   'city': 'Canada_6',
                                                                   'left': None,
                                                                   'right': None},
                                                               'right': None},
                                                           'right': None},
                                                       'right': None},
                                                   'right': None},
                                               'right': None},
                                           'right': None},
                                       'right': None},
                                   'right': None},
                               'right': None}},
                  'right': None},
              'right': {'city': 'Augusta', 'left': {'city': 'Columbia',
                                                    'left': {
                                                        'city': 'Florence',
                                                        'left': {
                                                            'city': 'Raleigh',
                                                            'left': {
                                                                'city': 'Richmond',
                                                                'left': {
                                                                    'city': 'Charlottesville',
                                                                    'left': {
                                                                        'city': 'Green_Bank',
                                                                        'left': {
                                                                            'city': 'Bridgeport',
                                                                            'left': {
                                                                                'city': 'Pittsburgh',
                                                                                'left': {
                                                                                    'city': 'Clarion',
                                                                                    'left': {
                                                                                        'city': 'Salamanca',
                                                                                        'left': {
                                                                                            'city': 'Buffalo_2',
                                                                                            'left': {
                                                                                                'city': 'Canada_5',
                                                                                                'left': None,
                                                                                                'right': None},
                                                                                            'right': None},
                                                                                        'right': None},
                                                                                    'right': None},
                                                                                'right': None},
                                                                            'right': None},
                                                                        'right': None},
                                                                    'right': None},
                                                                'right': {
                                                                    'city': 'Fredericksburg',
                                                                    'left': {
                                                                        'city': 'Baltimore',
                                                                        'left': {
                                                                            'city': 'Westminster',
                                                                            'left': {
                                                                                'city': 'Harrisburg',
                                                                                'left': {
                                                                                    'city': 'Mansfield',
                                                                                    'left': {
                                                                                        'city': 'Elmira',
                                                                                        'left': {
                                                                                            'city': 'Canada_4',
                                                                                            'left': None,
                                                                                            'right': None},
                                                                                        'right': None},
                                                                                    'right': None},
                                                                                'right': None},
                                                                            'right': None},
                                                                        'right': None},
                                                                    'right': None}},
                                                            'right': None},
                                                        'right': None},
                                                    'right': None},
                        'right': None}}, 'right': None},
     'right': {'city': 'Tallahassee', 'left': {'city': 'Birmingham', 'left': {'city': 'Huntsville',
                                                                              'left': {'city': 'Selmer',
                                                                                       'left': {'city': 'Memphis',
                                                                                                'left': {
                                                                                                    'city': 'Springfield',
                                                                                                    'left': {
                                                                                                        'city': 'St_Louis',
                                                                                                        'left': {
                                                                                                            'city': 'Champaign',
                                                                                                            'left': {
                                                                                                                'city': 'Chicago',
                                                                                                                'left': {
                                                                                                                    'city': 'Grand_Rapids',
                                                                                                                    'left': {
                                                                                                                        'city': 'Port_Huron',
                                                                                                                        'left': {
                                                                                                                            'city': 'Canada_2',
                                                                                                                            'left': None,
                                                                                                                            'right': None},
                                                                                                                        'right': None},
                                                                                                                    'right': None},
                                                                                                                'right': None},
                                                                                                            'right': None},
                                                                                                        'right': None},
                                                                                                    'right': {
                                                                                                        'city': 'Kansas_City',
                                                                                                        'left': {
                                                                                                            'city': 'Des_Moines',
                                                                                                            'left': {
                                                                                                                'city': 'Mason_City',
                                                                                                                'left': {
                                                                                                                    'city': 'Minneapolis',
                                                                                                                    'left': {
                                                                                                                        'city': 'International_Falls',
                                                                                                                        'left': {
                                                                                                                            'city': 'Canada_1',
                                                                                                                            'left': None,
                                                                                                                            'right': None},
                                                                                                                        'right': None},
                                                                                                                    'right': None},
                                                                                                                'right': None},
                                                                                                            'right': None},
                                                                                                        'right': None}},
                                                                                                'right': None},
                                                                                       'right': None}, 'right': None},
                                               'right': None}, 'right': None}}
