# Generated by Django 3.0.2 on 2020-01-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('food', models.IntegerField()),
                ('water', models.IntegerField()),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('food_available', models.IntegerField()),
                ('water_available', models.IntegerField()),
                ('location_2', models.CharField(max_length=30)),
                ('food_available_2', models.IntegerField()),
                ('water_available_2', models.IntegerField()),
            ],
        ),
    ]
