# Generated by Django 3.0.3 on 2020-02-20 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('food', models.IntegerField()),
                ('water', models.IntegerField()),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('food_available', models.IntegerField()),
                ('water_available', models.IntegerField()),
                ('location_2', models.CharField(max_length=30)),
                ('food_available_2', models.IntegerField()),
                ('water_available_2', models.IntegerField()),
            ],
        ),
    ]
